version: 0.0
os: linux
files:
  - source: /index.js
    destination: /var/www/html/
  - source: /src/conferences.js
    destination: /var/www/html/src
  - source: /src/index.js
    destination: /var/www/html/src
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
