version: 0.0
os: linux
files:
  - source: /
    destination: /backend/api
  # - source: src/conferences.js
  #   destination: /backend/api/src
  # - source: src/index.js
  #   destination: /backend/api/src
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
