version: 0.0
os: linux
files:
  - source: /index.js
    destination: /backend/
  - source: /src/conferences.js
    destination: /backend/src/
  - source: /src/teams.js
    destination: /backend/src/
  - source: /src/index.js
    destination: /backend/src/
  - source: /package.json
    destination: /backend/
hooks:
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
